### ISSUE TITLE
Regression on collect/classification?

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#25] opened 2017-01-26 21:25 UTC
With previous versions `collect` would print a report of the distribution of test inputs:
```
# let t = Test.make ~count:100_000 (make ~collect:string_of_int (Gen.int_bound 4)) (fun _ -> true);;
val t : QCheck.Test.t = QCheck.Test.Test <abstr>
# QCheck_runner.run_tests ~verbose:true [t];;                           
law <test>: 100000 relevant cases (100000 total)
  4: 20274 cases
  3: 19815 cases
  2: 19834 cases
  0: 20068 cases
  1: 20009 cases
success (ran 1 tests)
- : int = 0
```
But with the current master I cannot inspect the generation anymore:
```
# let t = Test.make ~count:100_000 (make ~collect:string_of_int (Gen.int_bound 4)) (fun _ -> true);;
val t : QCheck.Test.t = QCheck.Test.Test <abstr>
# QCheck_runner.run_tests ~verbose:true [t];;                           
random seed: 392026798
generated  error;  fail; pass / total       time -- test name
[✓] (100000)    0 ;    0 ; 100000 / 100000 --     1.2s -- anon_test_1
================================================================================
success (ran 1 tests)
- : int = 0
```
What's going on? A regression because of OUnit integration or an intentional change?

**Comment by Gbury** [comment] 2017-01-26 21:34
It seems I introduced that regression in a recent PR (#19 to be exact). The pull request was meant to give better output, but since I don't use `collect` much, I wasn't aware of that aspect of reporting. The idea of the new output is to have a single line by test during execution, and then print errors at the end (see https://github.com/c-cube/qcheck/blob/master/src/QCheck_runner.mli#L155 for an example of output).

Would it be okay for you if collect statistics were printed using roughly the same format as error and failures ?

**Comment by Gbury** [comment] 2017-01-26 23:24
PR #26 should fix the problem when it is merged.

**Comment by c-cube** [comment] 2017-01-26 23:26
@jmid I don't remember, would the `collect` results be displayed only in verbose mode, or always?

**Comment by c-cube** [comment] 2017-01-27 09:20
@jmid I can make a new release quickly if the fix from #26 satisfies you. Can you check with the current master branch?

**Comment by jmid** [comment] 2017-01-27 11:02
@Gbury : this format is great, thanks! The new output with checkmarks is also appreciated (and closer to the old <=v.0.3 QCheck output)

@c-cube : previously `collect` would only print with verbose mode on (which tricked both me and my students on the first run). I prefer the behaviour of PR #26 which always prints collect/classifications
but lets `~verbose` control the output of the remaining details, following the rationale "if I instrument one or more of my tests with classification I intend to see it, so print it". I would probably prefer `~verbose:true` to be the default, but that is separate discussion.

I have fetched master upstream and checked a few combinations: two tests with/without classifier and with/with classifier, and run both in the toplevel with/without verbose on. It seems to work great 👍

**Comment by c-cube** [comment] 2017-01-27 11:55
Ok then, I'll release soon. Sorry for the regression, but otoh I'm very happy with the way qcheck evolves thanks to contributions from you all!

**Comment by c-cube** [comment] 2017-01-27 14:41
https://github.com/ocaml/opam-repository/pull/8369 should fix that

**Closed by c-cube** 2017-01-27 14:41 UTC
