### ISSUE TITLE
regression :p

### ISSUE THREAD

**Issue by c-cube** [c-cube/qcheck#115] opened 2021-05-15 13:29 UTC
Since 4aadcd131b0086b0565b678ecbbcc11e0698d57f (by bisect) the examples do not work anymore, they hang on the first property (list_rev_involutive). It's probably in the conversion from tests from v1 to v2? The generators do not seem to have changed…

Also I suspect the shrinking in migrate-v1-v2 might be problematic as it's more eager, but we have no choice there.

@Sir4ur0n

**Comment by Sir4ur0n** [comment] 2021-05-19 14:27
How do you run those examples? I did not find a way to compile/run them (sorry if this is obvious :grin: )

**Comment by c-cube** [comment] 2021-05-19 14:37
`make example-***` or `dune exec examples/foo.exe` :)

**Comment by Sir4ur0n** [comment] 2021-05-26 13:33
There was **definitely** a laziness issue in the migrating function (shrink part), 7d9d465898127e748b917019c084b1199b5ad5a7 (part of the QCheck2 PR) fixes it

**Comment by c-cube** [comment] 2021-05-26 15:23
It's a hard problem, because it requires inversion of control :/

**Comment by Sir4ur0n** [comment] 2021-05-27 07:52
Yeah I don't manage to find a better solution for now...

So the current situation is: with QCheck2, QCheck1 shrinking has a significant perf regression (when shrinking is big), otherwise the runner example seems to work (if I comment out `long_shrink`):

QCheck2 branch:
![image](https://user-images.githubusercontent.com/1204125/119786756-cc009f80-bed0-11eb-9f08-7322c8175436.png)


`master` branch:
![image](https://user-images.githubusercontent.com/1204125/119785355-6a8c0100-becf-11eb-92ef-1e11efdb6ca6.png)


Note: comparing those allowed me to notice another regression regarding `assume`, `assume_fail` and `==>` which should now delegate to QCheck2. I have fixed it in f1d24773e5aa7dea176b7a6807c33de009be38cd

How do you want to proceed? Is this acceptable (I document it as part of the migration guide)?
If not: I currently don't have any idea

**Comment by Sir4ur0n** [comment] 2021-05-27 10:54
My 2 cents: I have a feeling that "document this risk but let it be that way" is acceptable considering:
* most developers (I would say "everyone" but it's never 100%, is it :grin: ) upgrade a dependency version when things work (CI green), not while working on a broken branch. So this shrinking perf regression would not be immediately breaking stuff when they migrate
* this is an incidental, unintentional nudge to migrate to QCheck2 :angel:

**Comment by c-cube** [comment] 2021-05-27 12:57
How about this: the real test type would be one that takes a bundle of:

- `'a gen`
- `'a print`
- either `' -> 'a iter` or `'a -> 'a seq` (as a sum type)

it means a tiny bit of wrapping for QCheck2 tests, but really, barely?

**Comment by Sir4ur0n** [comment] 2021-05-27 17:40
Sooooooo what you proposed was not directly possible because a QCheck2 `Gen.t` does not have a `'a -> 'a Seq.t` function :smile: 

But anyway I went a similar way (code is ugly IMHO but it does the job with minimal disturbance to the rest of the code), you can see it in a910955e8b9648a317de53a7685a8b8bd06ec986

The runner passes just like on `master` with this change.

In essence, the change is:
* Store an optional QCheck1 `shrink` function in `QCheck2.Test.cell`
* Add an ugly `make_cell_from_QCheck1` function to `QCheck2.Test`, which (basically) takes a `QCheck1.arbitrary` (deconstructed for cyclic-dependency reasons)
* `QCheck1.Test.make_cell` calls `QCheck2.Test.make_cell_from_QCheck1`
* During shrinking, if there is a QCheck1 `shrink` function, use it like in QCheck1. Otherwise, use the new QCheck2 integrated shrinking

I'm not proud of the code, but my main goal was to limit the impact/complexity increase on the "good" QCheck2 code.

**Comment by Sir4ur0n** [comment] 2021-06-04 21:23
I propose we close this issue?

**Closed** 2021-06-04 23:37 UTC
Labels: bug
